# Generated by Django 4.0.6 on 2022-09-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dev', '0002_alter_registration_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='password_name',
            new_name='password',
        ),
    ]
