# Generated by Django 4.0.6 on 2022-09-17 10:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dev', '0004_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('mobile_no', models.BigIntegerField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 17, 15, 45, 11, 727339))),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dev.registration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dev.product')),
            ],
        ),
    ]
