# Generated by Django 4.0.6 on 2022-09-17 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dev', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 16, 18, 44, 440800)),
        ),
    ]
